version: "3"
services:
    frontend:
        container_name: react-app
        build:
            context: ./client
            dockerfile: Dockerfile
        image: felipe/react-app
        ports:
            - "3000:3000"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: api-server
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: felipe/api-server
        ports:
            - "5000:5000"
        volumes:
            - ./backend:/usr/src/app